/*
 * Copyright (c) 2019 - GraphLoom contributors (github.com/jiefenn8/graphloom
 * This software is made available under the terms of Apache License, Version 2.0.
 */

package com.github.jiefenn8.graphloom.api;

import com.github.jiefenn8.graphloom.api.inputsource.Entity;
import org.apache.jena.rdf.model.RDFNode;

/**
 * This interface defines the base method that manages the mapping of any
 * nodes to their graph node term.
 */
public interface NodeMap {

    /**
     * Returns a generated term as a node for an entity with the given record
     * containing the property value required by this node map.
     *
     * @param record the record of entity to generate term form
     * @return the node term generated by this node map
     */
    @Deprecated
    RDFNode generateNodeTerm(Record record);

    /**
     * Returns a generated term as a node for an entity with the given record
     * containing the property value required by this node map.
     *
     * @param entity the record of entity to generate term form
     * @return the node term generated by this node map
     */
    RDFNode generateNodeTerm(Entity entity);

}
