/*
 * Copyright (c) 2019 - GraphLoom contributors (github.com/jiefenn8/graphloom
 * This software is made available under the terms of Apache License, Version 2.0.
 */

package com.github.jiefenn8.graphloom.api;

import com.github.jiefenn8.graphloom.api.inputsource.Entity;
import org.apache.jena.rdf.model.Resource;

import java.util.List;

/**
 * This interface defines the base methods that manages the mapping
 * of entity properties to their graph entity terms.
 */
public interface PropertyMap {

    /**
     * Generates an entity term with this map using the given entity to
     * retrieve any data needed.
     *
     * @param entity containing any data needed to generate term
     * @return the URI generated by this property map
     */
    Resource generateEntityTerm(Entity entity);


    /**
     * Returns a list of all class associated with the entity.
     *
     * @return the list with all class associated to entity as URIs
     */
    List<Resource> listEntityClasses();
}
