/*
 * Copyright (c) 2019 - GraphLoom contributors (github.com/jiefenn8/graphloom
 * This software is made available under the terms of Apache License, Version 2.0.
 */

package com.github.jiefenn8.graphloom.api;

import org.apache.jena.rdf.model.Resource;

import java.util.List;

/**
 * This interface defines the base methods that manages the mapping
 * of entity properties to their graph entity terms.
 */
public interface PropertyMap {
    /**
     * Returns a generated term as a node for an entity with the given record
     * containing the entity value required by this property map.
     *
     * @param record the record of entity to generate term form
     * @return the URI generated by this property map
     */
    Resource generateEntityTerm(Record record);

    /**
     * Returns a list of all class associated with the entity.
     *
     * @return the list with all class associated to entity as URIs
     */
    List<Resource> listEntityClasses();
}
