/*
 *    Copyright (c) 2019 - Javen Liu (github.com/jiefenn8)
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package com.github.jiefenn8.graphloom.api;

import org.apache.jena.rdf.model.Resource;

import java.util.List;

/**
 * This interface defines the base methods that manages the mapping
 * of entity properties to their graph entity terms.
 */
public interface PropertyMap {
    /**
     * Returns a generated term as a node for an entity with the given record
     * containing the entity value required by this property map.
     *
     * @param r record of entity to generate term form
     * @return the URI generated by this property map
     */
    Resource generateEntityTerm(Record r);

    /**
     * Returns a list of all class associated with the entity.
     *
     * @return the list with all class associated to entity as URIs
     */
    List<Resource> listEntityClasses();
}
