/*
 * Copyright (c) 2019 - GraphLoom contributors (github.com/jiefenn8/graphloom
 * This software is made available under the terms of Apache License, Version 2.0.
 */

package com.github.jiefenn8.graphloom.api;

import com.github.jiefenn8.graphloom.api.inputsource.Entity;
import com.github.jiefenn8.graphloom.util.UniqueId;
import org.apache.jena.rdf.model.Property;

/**
 * This interface defines the base methods that manages the mapping
 * of relation to their graph relation term.
 */
public interface RelationMap extends UniqueId {

    /**
     * Generates a relation term with this map using the given entity to
     * retrieve any data needed.
     *
     * @param entity containing any data needed to generate term
     * @return the URI generated by this relation map
     */
    Property generateRelationTerm(Entity entity);
}
