/*
 * Copyright (c) 2019 - GraphLoom contributors (github.com/jiefenn8/graphloom
 * This software is made available under the terms of Apache License, Version 2.0.
 */

package com.github.jiefenn8.graphloom.api;

import com.github.jiefenn8.graphloom.api.inputsource.Entity;
import org.apache.jena.rdf.model.Property;

/**
 * This interface defines the base methods that manages the mapping
 * of relation to their graph relation term.
 */
public interface RelationMap {

    /**
     * Returns a generated term as a node for an entity with the given record
     * containing the property name required by this relation map.
     *
     * @param entity the record of entity to generate term form
     * @return the URI generated by this relation map
     */
    Property generateRelationTerm(Entity entity);
}
