dist: trusty
language: java
jdk: oraclejdk8

before_install:
 - chmod +x gradlew
 
after_success:
 - bash <(curl -s https://codecov.io/bash)
 
deploy:
  provider: script
  dry_run: true
  skip_cleanup: true 
  script: ./gradlew bintrayUpload 
  on: 
    tags: true 
    branch: master
    