/*
 * Copyright (c) 2019 - GraphLoom contributors (github.com/jiefenn8/graphloom
 * This software is made available under the terms of Apache License, Version 2.0.
 */

package com.github.jiefenn8.graphloom.rdf.r2rml;

import com.github.jiefenn8.graphloom.api.Record;
import org.apache.jena.rdf.model.RDFNode;

/**
 * This interface defines the base methods that manages the common mapping of
 * any given source to their respective rdf terms.
 */
public interface TermMap {

    /**
     * Returns a generated term node using the provided entity
     * properties collections. The type of term node returned
     * depends on any class term type declared.
     *
     * @param record the record of entity to generate term form
     * @return the term node generated by this term map
     */
    RDFNode generateRDFTerm(Record record);

    /**
     * The TermType to return generated term as.
     */
    enum TermType {
        UNDEFINED, IRI, BLANK, LITERAL
    }
}
